### ISSUE TITLE
MacBook support?

### ISSUE THREAD

**Issue by GhostieSpook** [Yaekith/Discord-Block-Bypass-Meme#1]
Am I able to run and use this on mac?

**Comment by Yaekith** [comment]
No clue, haven't tested.

**Comment by Yaekith** [comment]
I use windows myself though.

**Comment by Picoseconds** [comment]
Yes, with a software called mono.

**Comment by Picoseconds** [comment]
@GhostieSpook You can download a software called Mono, and use the mono command to run the .exe file.
Like `mono DiscordBlockBypass.exe`
